sudo: required
services:
  - docker

before_install:
  - docker build -t jfgf11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jfgf11/react-test npm test -- -- coverage

after_success:
  - docker build -t jfgf11/multi-client ./client
  - docker build -t jfgf11/multi-nginx ./nginx
  - docker build -t jfgf11/multi-server ./server
  - docker build -t jfgf11/multi-worker ./worker
